FROM python:3.9-alpine

ENV CELERY_BROKER_URL redis://redis:6379/0
ENV CELERY_RESULT_BACKEND redis://redis:6379/0
ENV C_FORCE_ROOT true

ENV TZ=Asia/Shanghai


COPY . /queue
WORKDIR /queue

RUN pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple

# hot code reloading
ENTRYPOINT watchmedo auto-restart --directory=./ --pattern=*.py --recursive -- celery -A tasks worker --concurrency=1 --loglevel=INFO